# Generated by Django 2.2.12 on 2020-10-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useradmin',
            name='password',
            field=models.CharField(default='0', max_length=20),
        ),
    ]
