# Generated by Django 2.2.12 on 2020-10-16 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminlog', '0002_useradmin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradmin',
            name='password',
            field=models.CharField(max_length=20),
        ),
    ]
