# Generated by Django 2.2.12 on 2020-10-15 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forall', '0001_initial'),
        ('C', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_c',
            name='level_ID_C',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='student_level_C', to='forall.Levels'),
            preserve_default=False,
        ),
    ]
