# Generated by Django 2.2.12 on 2020-10-15 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activites_student_teacher',
            new_name='Activites_student_teacher_A',
        ),
        migrations.RenameModel(
            old_name='Student_Course',
            new_name='Student_Course_A',
        ),
    ]
