# Generated by Django 2.2.12 on 2020-10-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A', '0004_auto_20201019_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher_a',
            name='image',
        ),
    ]
